services:
  # Nuxt приложение
  app:
    image: sterks/techbit-site:latest
    container_name: techbit-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - NITRO_HOST=0.0.0.0
      - NITRO_PORT=3000
    env_file:
      - .env
    networks:
      - techbit-network
    volumes:
      - ./uploads:/app/uploads  # Для загрузки файлов (если понадобится)

  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: techbit-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/sites-available:/etc/nginx/sites-available:ro
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled:ro
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - app
    networks:
      - techbit-network

  # Certbot для SSL сертификатов
  certbot:
    image: certbot/certbot
    container_name: techbit-certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email runov.denis@yandex.ru --agree-tos --no-eff-email --staging -d techbit.su -d www.techbit.su
    depends_on:
      - nginx

  # Автообновление сертификатов
  certbot-renewal:
    image: certbot/certbot
    container_name: techbit-certbot-renewal
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    command: renew --webroot --webroot-path=/var/www/html
    restart: unless-stopped

volumes:
  certbot-etc:
  certbot-var:
  web-root:

networks:
  techbit-network:
    driver: bridge
