version: '3.8'

services:
  # Nuxt приложение
  app:
    image: sterks/techbit-site:latest
    container_name: techbit-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - NITRO_HOST=0.0.0.0
      - NITRO_PORT=3000
    env_file:
      - .env
    networks:
      - techbit-network
    volumes:
      - ./uploads:/app/uploads

  # Nginx reverse proxy (только HTTP)
  nginx:
    image: nginx:alpine
    container_name: techbit-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/sites-available/techbit-http.conf:/etc/nginx/conf.d/default.conf:ro
      - web-root:/var/www/html
    depends_on:
      - app
    networks:
      - techbit-network

volumes:
  web-root:

networks:
  techbit-network:
    driver: bridge
